# Generated by Django 6.0.5 on 2026-06-12 19:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(default='defaultemail@example.com', max_length=254, unique=True)),
                ('username', models.CharField(default='Trader', max_length=50, unique=True)),
                ('first_name', models.CharField(default='FirstName', max_length=50)),
                ('last_name', models.CharField(default='LastName', max_length=50)),
                ('phone', models.CharField(blank=True, default='000-000-0000', max_length=15)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=5)),
                ('budget', models.DecimalField(decimal_places=2, default=5000.0, max_digits=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default='stock/media/profile_pictures/profile.jpg', upload_to='static/stock/media/profile_pictures/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='SYMBL', max_length=10, unique=True)),
                ('name', models.CharField(default='Default Stock', max_length=100)),
                ('market', models.CharField(default='Unknown Market', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('current_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('portfolio_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('portfolio_name', models.CharField(default='My Portfolio', max_length=100)),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dividend_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payout_date', models.DateField(default=django.utils.timezone.now)),
                ('stock', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('bs', 'bought_then_sold')], default='buy', max_length=4)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price_per_share', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('portfolio', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stock.portfolio')),
                ('stock', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(default='Default Setting', max_length=100)),
                ('setting_value', models.CharField(blank=True, default='Default Value', max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'stock')},
            },
        ),
    ]
