# Generated by Django 6.0.5 on 2026-06-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
