# Generated by Django 5.1.1 on 2024-10-21 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_portfolio_id_portfolio_portfolio_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
