# Generated by Django 5.1.1 on 2024-10-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]


