# Generated by Django 5.1.1 on 2024-10-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_alter_portfolio_portfolio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_id',
            field=models.BigAutoField(default=100000, primary_key=True, serialize=False),
        ),
    ]
