# Generated by Django 5.1.1 on 2024-10-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile_pictures/profile.jpg', upload_to='media/profile_pictures/'),
        ),
    ]
