# Generated by Django 5.1.1 on 2024-10-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='stock/media/profile_pictures/profile.jpg', upload_to='static/stock/media/profile_pictures/'),
        ),
    ]
